### PR TITLE
Weights & Biases Integration for Inference

### PR DESCRIPTION
**Pull request by parambharat**
This PR has the following modifications and feature improvements:
 
 - adds short cli argument `o` for `output` in demo
 - stores image to image file output file or directory if output path is provided in cli args
 - replaces forever while loop with for loop in inference iterations
 - Adds support for logging inference results to [Weights & Biases](https://wandb.ai/site).
 - easily log our results to Weights & Biases
 - explore and analyze the bounding box and sematic mask predictions using a simple and intuitive user interface.

 Link to Weights & Biases Dashboard: https://wandb.ai/parambharat/yolov7?workspace=user-parambharat

### CODE REVIEW

**Comment by jinfagang** [comment]
@parambharat Hi, thanks for contributing! Can u revert the README the readme shouldn't be changed for this feature.

**Comment by parambharat** [comment]
Hi @jinfagang , Thank you for the quick response. I just noticed that the README was formatted automatically by my IDE. I will revert these formatting changes

However, I wanted to inform users about the wandb logging feature and therefore included the following below the instructions to run the demo in the readme.


> Run a quick demo to upload and explore your YOLOv7 prediction with [Weights & Biases](https://wandb.ai/site)
. [Here's an example dashboard](https://wandb.ai/parambharat/yolov7)

```
python3 demo.py --config-file configs/wearmask/darknet53.yaml --input ./datasets/wearmask/images/val2017 --wandb-entity <your-username/team> --wandb-project <project-name> --opts MODEL.WEIGHTS output/model_0009999.pth
```

Let me know if you prefer an alternative way to inform users about the feature.

**Comment by jinfagang** [comment]
@parambharat It's OK add a instruction in readme. Keep elsewhere in right format. 

I am also want to know why Wanda db needed in demo rather than in training? I am not familiar with Wandadb but it's a good thing, does demo benefit more than in training?

**Comment by jinfagang** [comment]
@parambharat thanks, will merge it.

**Pull request merged**
